-- AlterTable products
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) DEFAULT 12.00;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "hsnCode" TEXT DEFAULT '6203';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isTaxExempt" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable orders
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "tax" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "cgst" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "sgst" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "igst" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "taxDetails" JSONB;

-- AlterTable order_items
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) DEFAULT 12.00;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "tax" DECIMAL(12,2) DEFAULT 0;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "hsnCode" TEXT DEFAULT '6203';

-- CreateTable tax_settings
CREATE TABLE IF NOT EXISTS "tax_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "originState" TEXT NOT NULL DEFAULT 'Delhi',
    "gstin" TEXT NOT NULL DEFAULT '',
    "defaultGstRate" DECIMAL(5,2) NOT NULL DEFAULT 12.00,
    "priceInclusive" BOOLEAN NOT NULL DEFAULT true,
    "defaultHsn" TEXT NOT NULL DEFAULT '6203',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tax_settings_pkey" PRIMARY KEY ("id")
);
